In [1]:
import numpy as np

In [2]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

In [3]:
a + 5

array([5, 6, 7])

In [4]:
M = np.ones((3, 3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
M+a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [6]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]
print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [7]:
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [8]:
# Broadcasting example 1

In [9]:
M = np.ones((2, 3))
a = np.arange(3)

In [10]:
M+a

array([[1., 2., 3.],
       [1., 2., 3.]])

In [11]:
# Broadcasting example 2

In [12]:
a = np.arange(3).reshape((3, 1))
b = np.arange(3)

In [15]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [17]:
# Broadcasting example 3

In [18]:
M = np.ones((3, 2))
a = np.arange(3)

In [19]:
M+a

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 