In [4]:
import study_QAHA7AI01_py as m
import numpy as np

In [5]:
#Python Code
result=0
for i in range(100):
        result+=i
print(result)

4950


In [6]:
# Single integer in Python contains 4 pieces
#      - ob_refcnt
#      - ob_type
#      - ob_size
#      - ob_digit

In [7]:
# integer array
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [8]:
# forced float array
np.array([1,4,2,5,3],dtype='float32')

array([1., 4., 2., 5., 3.], dtype=float32)

In [9]:
# nested lists result in multidimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [10]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
#Create a 3x5 floating-point array filled with 1s
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [13]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [15]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.52677206, 0.50243907, 0.35960335],
       [0.4928797 , 0.37092751, 0.80406671],
       [0.81622088, 0.12061625, 0.34676315]])

In [16]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 0.96827221, -0.31366341, -1.51050157],
       [ 0.30158009,  1.45204223,  1.13053827],
       [ 0.66067131, -0.52674861,  2.06686966]])

In [17]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[8, 5, 7],
       [9, 9, 0],
       [7, 6, 0]])

In [18]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that
# memory location
np.empty(3)

array([1., 1., 1.])